Update to 2022
perladvent/perl-advent-cfp pull request #2
Opened 2022-07-08 21:56 UTC by simbabque

I've updated all of the dates to fit 2022. There are a few fixed typos, and I have removed the Google Plus share button, because G+ is gone.

Two things still need doing:

- There is a link to a Google form. This is out of date. The form exists, but has an old date. We also don't have access to this form.
- Contact details for questions in accepted.md point to Mark's email address. My suggestion would be to replace this with the URL for raising issues in the actual blog repository, so that people who have accepted can raise an issue there and everyone who's involved in running the project can help.

We might just open issues for these.

2022-07-09 03:36 UTC, oalders requested changes
Just a couple of typos from the original text.

2022-07-09 03:36 UTC, oalders commented on _config.yml
> +description: The Call For Partipation for the 2022 Perl Advent Calendar
Participation

2022-07-09 03:36 UTC, oalders commented on _includes/sharing.html
> +      <a href="mailto:?subject=The%202022%20Perl%20Adevent%20Calendar%20CFP%20is%20open%20http%3A%2F%2Fcfp.perladvent.org%2F">
Advent

2022-07-09 11:48 UTC, simbabque commented
Nice, thanks. I think that's it. 

There is a whole `_site` directory in there, which I think was the original generated output. My local Jekyll has regenerated that, but I haven't checked it in so far. It looks like it was out of date, no other recent commits have touched it. Maybe we delete it to see what happens.

2022-07-10 13:58 UTC, oalders approved these changes
⭐

2022-07-10 13:59 UTC, oalders commented
> Maybe we delete it to see what happens.

Yes, I was a bit surprised to see generated files in being tracked. That would be worth doing, I think.

2022-07-10 14:00 UTC, merged